name: UI5 CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code
    - uses: actions/checkout@v4

    # 2️⃣ Setup Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    # 3️⃣ Go into webapp folder (where ui5.yaml is)
    - run: cd app
    - run: cd project1
    - run: cd webapp
    

    # 4️⃣ Install dependencies
    - run: npm install

    # 5️⃣ Install UI5 CLI locally
    - run: npm install --save-dev @ui5/cli

    # 6️⃣ Run UI5 build
    - run: npm run build
